from os.path import join
import itertools
import pandas as pd

configfile: 'config/config.yml'

if config['run_cohort'] == None:
    cohorts = config['cohorts']
else:
    cohorts = [config['run_cohort']]

subjects = dict()
all_subjects = list()
for cohort in config['cohorts']:
    subjects[cohort] = [s for s in pd.read_table(config['participants_tsv'][cohort]).participant_id.to_list()]
    all_subjects = all_subjects + subjects[cohort]

print(all_subjects)

channels = list(config['in_images'].keys())
aux_channels = list(config.get('aux_images', {}).keys())

wildcard_constraints:
    iteration="[0-9]+",
    cohort="[a-zA-Z0-9]+"

if config['run_iter'] != None:
    rule all_iter:
        input:
            expand(
                'results/cohort-{cohort}/iter_{iter}/template_{channel}.nii.gz',
                cohort=cohorts,
                channel=channels,
                iter=[config['run_iter']]
            ),
            expand(
                'results/cohort-{cohort}/iter_{iter}/aux_template_{aux_channel}.nii.gz',
                cohort=cohorts,
                aux_channel=aux_channels,
                iter=range(1, int(config['run_iter']) + 1)
            ) if len(aux_channels) > 0 else [],
            expand(
                "results/cohort-{cohort}/iter_{iter}/prob_atlas/prob_atlas_{channel}_4D.nii.gz",
                cohort=config['cohorts'],
                iter=config['run_iter'],
                channel=channels
            ),
            expand(
                "results/cohort-{cohort}/iter_{iter}/prob_atlas/{subject}_iter{iter}_euclidean_distance.csv",
                cohort=config['cohorts'],
                subject=all_subjects,
                iter=config['run_iter']
            )
            

include: 'rules/ants_template.smk'