#for template building - mix of fmriprep and internally processed-data
in_images:
  T1w: "/nfs/khan/trainees/mliu366/2_histo3D_reg/subj-reg/01_rigid_init/snakeinput_t20temp/T1w/{subject}_hemi-L_T1w.nii.gz"

aux_images:
  LH_R1map: '/nfs/khan/trainees/mliu366/2_histo3D_reg/subj-reg/01_rigid_init/snakeinput_t20temp/R1/{subject}_hemi-L_R1map.nii.gz'

in_dseg:
  T1w: '/nfs/khan/trainees/mliu366/2_histo3D_reg/subj-reg/01_rigid_init/snakeinput_t20temp/dseg/{subject}_hemi-L_dseg3.nii.gz'

in_lut:
  T1w: '/nfs/khan/trainees/mliu366/2_histo3D_reg/subj-reg/01_rigid_init/snakeinput_t20temp/dseg/{subject}_hemi-L_LUT.txt'

atlas_labels:
  - 1
  - 2
  - 3
  - 4
  - 5
  - 6
  - 7
  - 8
  - 9

cohorts:
  - 'T20test'

participants_tsv:
  T20test: 'config/participants.tsv'


resolution_index: 0.05 # res-{resolution_index}  
#shape, zooms, origin will be obtained from the nifti itself

#for templateflow-style output
template_name: 'T20test'  #tpl-{template_name} 

#assumes that templateflow templates are linked in resources folder
init_template:
  T1w: '/nfs/khan/trainees/mliu366/2_histo3D_reg/subj-reg/01_rigid_init/snakeinput_t20temp/T1w/sub-T20_hemi-L_T1w.nii.gz'

#keep this empty, is set by command-line ( --config run_iter=1 or --config run_cohort=young)
run_cohort: 
run_iter: 10

#this is the iter which is exported into templateflow format
max_iters: 10


resample_init_template: False #set this True to resample init template to below dims 
# # WARNING - changing this can significantly alter memory usage and run-time -- 
# resample_vox_dims: 
#  - .05
#  - .05
#  - .05


#should be at least 2.3.4 (includes --random-seed option, and fixes some argparsing bugs)
singularity:
  ants: '/nfs/khan/trainees/msalma29/amygdala_project/atlas/scripts/singularity/ants_2.3.4.sif'
  itksnap:  '/nfs/khan/trainees/msalma29/amygdala_project/atlas/scripts/singularity/itksnap_latest.sif'
  prepdwi: '/nfs/khan/trainees/msalma29/amygdala_project/atlas/scripts/singularity/prepdwi_latest.sif'  


ants:
  dim: 3
  shape_update:
      gradient_step: 0.25



