#for template building - mix of fmriprep and internally processed-data
in_images:
  LH_T2w: '/nfs/khan/trainees/msalma29/amygdala_project/atlas/scripts/data_94T/training/images/{subject}_ses-000_hemi-L.nii.gz'

# in_labels:
#   LH_T2w: '/nfs/khan/trainees/msalma29/amygdala_project/atlas/scripts/data_94T_aligned/training/labels/{subject}_ses-000_hemi-L.nii.gz'


# #for naming the final files in templateflow output
# bids_suffix:
#   RH_T2w: 'desc-brain_T1w'

cohorts:
  - 'adult94TLabeledROILH'

participants_tsv:
  adult94TLabeledROILH: 'config/participants_adult_94T.tsv'


resolution_index: 0.05 # res-{resolution_index}  
#shape, zooms, origin will be obtained from the nifti itself

#for templateflow-style output
template_name: 'Amygdala_RH_94T'  #tpl-{template_name} 

#assumes that templateflow templates are linked in resources folder
init_template:
  LH_T2w: '/nfs/khan/trainees/msalma29/amygdala_project/atlas/scripts/data_94T/training/images/sub-2092_ses-000_hemi-L.nii.gz'

#  LH_T2w: '/home/myaser/scratch/template_building/iter_90_atlas_p2mm/template_LH_T2w_p1mm.nii.gz'

# mask_template:
#   LH_T2w: '/nfs/khan/trainees/msalma29/amygdala_project/atlas/scripts/averaged_masked_94T_to_mni/{subject}_desc-T2wAverage_mni_dseg.nii.gz'


# #will register cohort templates to the std template after they are generated
# std_template_name: 'sub-2054_ses-RH_Template'

#keep this empty, is set by command-line ( --config run_iter=1 or --config run_cohort=young)
run_cohort: 
run_iter: 

#this is the iter which is exported into templateflow format
max_iters: 10


resample_init_template: False #set this True to resample init template to below dims 
# # WARNING - changing this can significantly alter memory usage and run-time -- 
# resample_vox_dims: 
#  - .05
#  - .05
#  - .05


#should be at least 2.3.4 (includes --random-seed option, and fixes some argparsing bugs)
singularity:
  ants: '/nfs/khan/trainees/msalma29/amygdala_project/atlas/scripts/singularity/ants_2.3.4.sif'
  itksnap:  '/nfs/khan/trainees/msalma29/amygdala_project/atlas/scripts/singularity/itksnap_latest.sif'
  prepdwi: '/nfs/khan/trainees/msalma29/amygdala_project/atlas/scripts/singularity/prepdwi_latest.sif'  


ants:
  dim: 3
  shape_update:
      gradient_step: 0.25 



